language: node_js
node_js:
  - "node"
cache: npm
branches:
  only:
    - master
script: npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "e8dmBR0rDLT7wBwWscWVU5PTd3PDTyFBhjMuUPeOdBN2O5xAfDpXD48zbTEIF60IN2dCueGmdxJox1QBnUVdKfxshGCJiIUKr+nehfCzS4J9Kj9eGg1i/ujpIi4yR+dGNN+utQE64GktDxMMIJBrGNyIsUsOBsu0ill9esE8j5ORN/o1/7u/cO4RpmpsHyLe2VTI1WzZvEkzFs9bkohU4Enf7dWmGu4f8DFqDSc2kumWvsUjBJ7Nbt9iUM2whaQ0seqTVobY6P5Y0+6TLwXMMHYkegQH5b7gpeBjR+wl1Ax7J45UnMI8fw8CXSBS0VfTDZVGnZDeU5+pzYPrhQEVQQtiqs85wMoJuqgn8UH3B/xcn/BdOl77Lw6z4hqFmnqS+I9W0wW2FK+gJBUoG4q/l/y9u2CFILJxDDrgb6TjEOxJFsFZSS8LTsPLRMSXipYqfI5XXgtVXQTos1Xsvu42eBwGjhbIuIhmJu2ZJMMb6LftXiVcTkOkSjgOCaBrRJ8SIdsF2N9zzbX32P2YlacKV9g5bf7dG0nSTTktmkCPstrideWaWtKdU0TPLeFTIqRqvaz3XEBR519Kv1gXuSEyJnMtWHRhNDo+7M2gBNQOTGRwHJmbxn1lu2Hzb/Ju0ycDi6CXfg5+qIWr/adOOhGYk0DrwYawe7URQHASlcLQznc="
